packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  netlify-cli: true
  react-native-nitro-modules: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true
  workerd: true
verifyDepsBeforeRun: false
