/// <reference types="node" />

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface IconifyIcon {
  body: string;
  height?: number;
  width?: number;
}

interface IconifyCollection {
  height?: number;
  icons: Record<string, IconifyIcon>;
  width?: number;
}

const iconNames = [
  "fa6-solid:pause",
  "fa6-solid:play",
  "fa6-solid:check",
  "fa6-solid:cloud",
  "fa6-solid:filter",
  "fa6-solid:xmark",
  "fa6-solid:plus",
  "fa6-solid:arrow-left",
  "fa6-solid:file-lines",
  "fa6-solid:paintbrush",
  "fa6-solid:image",
  "fa6-solid:clock-rotate-left",
  "fa6-solid:ellipsis-vertical",
  "fa6-solid:list",
  "fa6-solid:file-import",
  "fa6-solid:house",
  "fa6-solid:gear",
  "fa6-solid:music",
  "fa6-solid:download",
  "fa6-solid:trash",
  "fa6-solid:pen",
  "fa6-solid:circle-info",
  "fa6-solid:arrow-up-from-bracket",
  "fa6-solid:magnifying-glass",
  "fa6-solid:images",
  "fa6-solid:file-export",
  "fa6-solid:check-double",
  "fa6-solid:circle-half-stroke",
  "fa6-solid:copy",
  "fa6-solid:trash-can",
  "fa6-solid:arrow-rotate-left",
  "fa6-solid:link",
  "fa6-solid:cloud-arrow-down",
  "fa6-solid:database",
  "fa6-solid:code",
  "fa6-solid:bug",
  "fa6-solid:share",
  "fa6-solid:list-check",
  "fa6-solid:angle-down",
  "fa6-solid:eye",
  "fa6-solid:floppy-disk",
  "fa6-solid:circle-up",
  "fa6-solid:award",
  "fa6-solid:circle-stop",
  "fa6-solid:face-kiss-wink-heart",
  "fa6-solid:arrows-up-down-left-right",
  "fa6-solid:rotate-left",
  "ion:checkmark-circle",
  "ion:information-circle",
  "ion:alert-circle",
  "ion:close-circle",
  "tabler:alert-square-rounded",
  "tabler:repeat-off",
  "tabler:repeat",
  "tabler:repeat-once",
  "tabler:arrows-right",
  "tabler:arrows-shuffle",
  "ri:skip-back-mini-fill",
  "uil:qrcode-scan",
  "mingcute:grid-fill",
  "material-symbols:speed-rounded",
] as const;

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageDirectory = join(scriptDirectory, "..");
const outputDirectory = join(packageDirectory, "src/assets/icons");
const registryPath = join(packageDirectory, "src/component/icon-map.generated.ts");
const collectionCache = new Map<string, IconifyCollection>();

mkdirSync(outputDirectory, { recursive: true });

function loadCollection(prefix: string) {
  const cached = collectionCache.get(prefix);
  if (cached) {
    return cached;
  }

  const packagePath = join(packageDirectory, `node_modules/@iconify-json/${prefix}/icons.json`);
  if (!existsSync(packagePath)) {
    throw new Error(`Iconify collection is not installed: ${prefix}`);
  }

  const collection = JSON.parse(readFileSync(packagePath, "utf8")) as IconifyCollection;
  collectionCache.set(prefix, collection);
  return collection;
}

function componentName(iconName: string) {
  return `${iconName
    .split(/[-:]/u)
    .map(part => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join("")}Icon`;
}

const generatedIcons = iconNames.map(iconName => {
  const [prefix, name] = iconName.split(":");
  const collection = loadCollection(prefix);
  const icon = collection.icons[name];

  if (!icon) {
    throw new Error(`Icon is missing from @iconify-json/${prefix}: ${name}`);
  }

  const width = icon.width ?? collection.width ?? 24;
  const height = icon.height ?? collection.height ?? 24;
  const fileName = `${prefix}--${name}.svg`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" fill="currentColor">\n  ${icon.body}\n</svg>\n`;

  writeFileSync(join(outputDirectory, fileName), svg);

  return {
    componentName: componentName(iconName),
    fileName,
    iconName,
  };
});

const imports = generatedIcons
  .map(({ componentName: name, fileName }) => `import ${name} from "../assets/icons/${fileName}";`)
  .join("\n");
const entries = generatedIcons.map(({ componentName: name, iconName }) => `  "${iconName}": ${name},`).join("\n");
const registry = `// Generated by pnpm extract-icons. Do not edit directly.\nimport type { FC } from "react";\nimport type { SvgProps } from "react-native-svg";\n\n${imports}\n\nexport const iconMap = {\n${entries}\n} satisfies Record<string, FC<SvgProps>>;\n\nexport type IconName = keyof typeof iconMap;\n`;

writeFileSync(registryPath, registry);
console.log(`Extracted ${generatedIcons.length} local SVG icons and updated ${registryPath}`);
