// Generated by pnpm extract-icons. Do not edit directly.
import type { FC } from "react";
import type { SvgProps } from "react-native-svg";

import Fa6SolidPauseIcon from "../assets/icons/fa6-solid--pause.svg";
import Fa6SolidPlayIcon from "../assets/icons/fa6-solid--play.svg";
import Fa6SolidCheckIcon from "../assets/icons/fa6-solid--check.svg";
import Fa6SolidCloudIcon from "../assets/icons/fa6-solid--cloud.svg";
import Fa6SolidFilterIcon from "../assets/icons/fa6-solid--filter.svg";
import Fa6SolidXmarkIcon from "../assets/icons/fa6-solid--xmark.svg";
import Fa6SolidPlusIcon from "../assets/icons/fa6-solid--plus.svg";
import Fa6SolidArrowLeftIcon from "../assets/icons/fa6-solid--arrow-left.svg";
import Fa6SolidFileLinesIcon from "../assets/icons/fa6-solid--file-lines.svg";
import Fa6SolidPaintbrushIcon from "../assets/icons/fa6-solid--paintbrush.svg";
import Fa6SolidImageIcon from "../assets/icons/fa6-solid--image.svg";
import Fa6SolidClockRotateLeftIcon from "../assets/icons/fa6-solid--clock-rotate-left.svg";
import Fa6SolidEllipsisVerticalIcon from "../assets/icons/fa6-solid--ellipsis-vertical.svg";
import Fa6SolidListIcon from "../assets/icons/fa6-solid--list.svg";
import Fa6SolidFileImportIcon from "../assets/icons/fa6-solid--file-import.svg";
import Fa6SolidHouseIcon from "../assets/icons/fa6-solid--house.svg";
import Fa6SolidGearIcon from "../assets/icons/fa6-solid--gear.svg";
import Fa6SolidMusicIcon from "../assets/icons/fa6-solid--music.svg";
import Fa6SolidDownloadIcon from "../assets/icons/fa6-solid--download.svg";
import Fa6SolidTrashIcon from "../assets/icons/fa6-solid--trash.svg";
import Fa6SolidPenIcon from "../assets/icons/fa6-solid--pen.svg";
import Fa6SolidCircleInfoIcon from "../assets/icons/fa6-solid--circle-info.svg";
import Fa6SolidArrowUpFromBracketIcon from "../assets/icons/fa6-solid--arrow-up-from-bracket.svg";
import Fa6SolidMagnifyingGlassIcon from "../assets/icons/fa6-solid--magnifying-glass.svg";
import Fa6SolidImagesIcon from "../assets/icons/fa6-solid--images.svg";
import Fa6SolidFileExportIcon from "../assets/icons/fa6-solid--file-export.svg";
import Fa6SolidCheckDoubleIcon from "../assets/icons/fa6-solid--check-double.svg";
import Fa6SolidCircleHalfStrokeIcon from "../assets/icons/fa6-solid--circle-half-stroke.svg";
import Fa6SolidCopyIcon from "../assets/icons/fa6-solid--copy.svg";
import Fa6SolidTrashCanIcon from "../assets/icons/fa6-solid--trash-can.svg";
import Fa6SolidArrowRotateLeftIcon from "../assets/icons/fa6-solid--arrow-rotate-left.svg";
import Fa6SolidLinkIcon from "../assets/icons/fa6-solid--link.svg";
import Fa6SolidCloudArrowDownIcon from "../assets/icons/fa6-solid--cloud-arrow-down.svg";
import Fa6SolidDatabaseIcon from "../assets/icons/fa6-solid--database.svg";
import Fa6SolidCodeIcon from "../assets/icons/fa6-solid--code.svg";
import Fa6SolidBugIcon from "../assets/icons/fa6-solid--bug.svg";
import Fa6SolidShareIcon from "../assets/icons/fa6-solid--share.svg";
import Fa6SolidListCheckIcon from "../assets/icons/fa6-solid--list-check.svg";
import Fa6SolidAngleDownIcon from "../assets/icons/fa6-solid--angle-down.svg";
import Fa6SolidEyeIcon from "../assets/icons/fa6-solid--eye.svg";
import Fa6SolidFloppyDiskIcon from "../assets/icons/fa6-solid--floppy-disk.svg";
import Fa6SolidCircleUpIcon from "../assets/icons/fa6-solid--circle-up.svg";
import Fa6SolidAwardIcon from "../assets/icons/fa6-solid--award.svg";
import Fa6SolidCircleStopIcon from "../assets/icons/fa6-solid--circle-stop.svg";
import Fa6SolidFaceKissWinkHeartIcon from "../assets/icons/fa6-solid--face-kiss-wink-heart.svg";
import Fa6SolidArrowsUpDownLeftRightIcon from "../assets/icons/fa6-solid--arrows-up-down-left-right.svg";
import Fa6SolidRotateLeftIcon from "../assets/icons/fa6-solid--rotate-left.svg";
import IonCheckmarkCircleIcon from "../assets/icons/ion--checkmark-circle.svg";
import IonInformationCircleIcon from "../assets/icons/ion--information-circle.svg";
import IonAlertCircleIcon from "../assets/icons/ion--alert-circle.svg";
import IonCloseCircleIcon from "../assets/icons/ion--close-circle.svg";
import TablerAlertSquareRoundedIcon from "../assets/icons/tabler--alert-square-rounded.svg";
import TablerRepeatOffIcon from "../assets/icons/tabler--repeat-off.svg";
import TablerRepeatIcon from "../assets/icons/tabler--repeat.svg";
import TablerRepeatOnceIcon from "../assets/icons/tabler--repeat-once.svg";
import TablerArrowsRightIcon from "../assets/icons/tabler--arrows-right.svg";
import TablerArrowsShuffleIcon from "../assets/icons/tabler--arrows-shuffle.svg";
import RiSkipBackMiniFillIcon from "../assets/icons/ri--skip-back-mini-fill.svg";
import UilQrcodeScanIcon from "../assets/icons/uil--qrcode-scan.svg";
import MingcuteGridFillIcon from "../assets/icons/mingcute--grid-fill.svg";
import MaterialSymbolsSpeedRoundedIcon from "../assets/icons/material-symbols--speed-rounded.svg";

export const iconMap = {
  "fa6-solid:pause": Fa6SolidPauseIcon,
  "fa6-solid:play": Fa6SolidPlayIcon,
  "fa6-solid:check": Fa6SolidCheckIcon,
  "fa6-solid:cloud": Fa6SolidCloudIcon,
  "fa6-solid:filter": Fa6SolidFilterIcon,
  "fa6-solid:xmark": Fa6SolidXmarkIcon,
  "fa6-solid:plus": Fa6SolidPlusIcon,
  "fa6-solid:arrow-left": Fa6SolidArrowLeftIcon,
  "fa6-solid:file-lines": Fa6SolidFileLinesIcon,
  "fa6-solid:paintbrush": Fa6SolidPaintbrushIcon,
  "fa6-solid:image": Fa6SolidImageIcon,
  "fa6-solid:clock-rotate-left": Fa6SolidClockRotateLeftIcon,
  "fa6-solid:ellipsis-vertical": Fa6SolidEllipsisVerticalIcon,
  "fa6-solid:list": Fa6SolidListIcon,
  "fa6-solid:file-import": Fa6SolidFileImportIcon,
  "fa6-solid:house": Fa6SolidHouseIcon,
  "fa6-solid:gear": Fa6SolidGearIcon,
  "fa6-solid:music": Fa6SolidMusicIcon,
  "fa6-solid:download": Fa6SolidDownloadIcon,
  "fa6-solid:trash": Fa6SolidTrashIcon,
  "fa6-solid:pen": Fa6SolidPenIcon,
  "fa6-solid:circle-info": Fa6SolidCircleInfoIcon,
  "fa6-solid:arrow-up-from-bracket": Fa6SolidArrowUpFromBracketIcon,
  "fa6-solid:magnifying-glass": Fa6SolidMagnifyingGlassIcon,
  "fa6-solid:images": Fa6SolidImagesIcon,
  "fa6-solid:file-export": Fa6SolidFileExportIcon,
  "fa6-solid:check-double": Fa6SolidCheckDoubleIcon,
  "fa6-solid:circle-half-stroke": Fa6SolidCircleHalfStrokeIcon,
  "fa6-solid:copy": Fa6SolidCopyIcon,
  "fa6-solid:trash-can": Fa6SolidTrashCanIcon,
  "fa6-solid:arrow-rotate-left": Fa6SolidArrowRotateLeftIcon,
  "fa6-solid:link": Fa6SolidLinkIcon,
  "fa6-solid:cloud-arrow-down": Fa6SolidCloudArrowDownIcon,
  "fa6-solid:database": Fa6SolidDatabaseIcon,
  "fa6-solid:code": Fa6SolidCodeIcon,
  "fa6-solid:bug": Fa6SolidBugIcon,
  "fa6-solid:share": Fa6SolidShareIcon,
  "fa6-solid:list-check": Fa6SolidListCheckIcon,
  "fa6-solid:angle-down": Fa6SolidAngleDownIcon,
  "fa6-solid:eye": Fa6SolidEyeIcon,
  "fa6-solid:floppy-disk": Fa6SolidFloppyDiskIcon,
  "fa6-solid:circle-up": Fa6SolidCircleUpIcon,
  "fa6-solid:award": Fa6SolidAwardIcon,
  "fa6-solid:circle-stop": Fa6SolidCircleStopIcon,
  "fa6-solid:face-kiss-wink-heart": Fa6SolidFaceKissWinkHeartIcon,
  "fa6-solid:arrows-up-down-left-right": Fa6SolidArrowsUpDownLeftRightIcon,
  "fa6-solid:rotate-left": Fa6SolidRotateLeftIcon,
  "ion:checkmark-circle": IonCheckmarkCircleIcon,
  "ion:information-circle": IonInformationCircleIcon,
  "ion:alert-circle": IonAlertCircleIcon,
  "ion:close-circle": IonCloseCircleIcon,
  "tabler:alert-square-rounded": TablerAlertSquareRoundedIcon,
  "tabler:repeat-off": TablerRepeatOffIcon,
  "tabler:repeat": TablerRepeatIcon,
  "tabler:repeat-once": TablerRepeatOnceIcon,
  "tabler:arrows-right": TablerArrowsRightIcon,
  "tabler:arrows-shuffle": TablerArrowsShuffleIcon,
  "ri:skip-back-mini-fill": RiSkipBackMiniFillIcon,
  "uil:qrcode-scan": UilQrcodeScanIcon,
  "mingcute:grid-fill": MingcuteGridFillIcon,
  "material-symbols:speed-rounded": MaterialSymbolsSpeedRoundedIcon,
} satisfies Record<string, FC<SvgProps>>;

export type IconName = keyof typeof iconMap;
